### ISSUE TITLE
debpython breaks Python 2<->3 compatibility

### ISSUE THREAD

**Issue by bittner** [bittner/pyclean#1]
I'm attempting to consolidate the three scripts for Python 2, Python 3 and PyPy into a single module. This turns out to be hard (read: "impossible") due to external dependencies.

When I make the syntax in the [pyclean.pyclean](https://github.com/bittner/pyclean/blob/master/pyclean/pyclean.py) module cross-version compatible the imports on top of the source file still fail when I run the tests with Python 3:
```python
Traceback (most recent call last):
  File "/home/foo/pyclean/.tox/py34/bin/pyclean", line 6, in <module>
    from pyclean.pyclean import main
  File "/home/foo/pyclean/.tox/py34/lib/python3.4/site-packages/pyclean/pyclean.py", line 20, in <module>
    from debpython.namespace import add_namespace_files
  File "/usr/share/python/debpython/namespace.py", line 120
    except (IOError, OSError), e:
                             ^
SyntaxError: invalid syntax
```

We would need to either:

- fix the debpython  package, or
- include the debpython package's code into our package

making it work across all recent (read: "supported") Python versions from a single code base in both cases.

Given the size, the dependencies and importance of the Debian project, I would guess the latter would be more reasonable and realistic to pursue.

An additional option would be to drop the debpython dependency entirely, but I honestly don't know what this entails.

**Comment by bittner** [comment]
This is seemingly addressed by the [python3-defaults](https://salsa.debian.org/cpython-team/python3-defaults/tree/master/debpython) project. Some simple [tests pass successfully](https://github.com/bittner/pyclean/pull/3) for both Python 2 and 3.
