### ISSUE TITLE
ModuleNotFoundError: No module named 'debpython' on Windows

### ISSUE THREAD

**Issue by PhilippSelenium** [bittner/pyclean#35]
Os: Win10
Python: 3.8.10
pyclean:  2.0.0

```
py3clean .
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Scripts\py3clean.exe\__main__.py", line 7, in <module>
  File "c:\\lib\site-packages\pyclean\cli.py", line 67, in py3clean
    main('CPython3')
  File "c:\lib\site-packages\pyclean\cli.py", line 50, in main
    impl = compat.get_implementation(override=override)
  File "c:\lib\site-packages\pyclean\compat.py", line 28, in get_implementation
    return import_module(module_name)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\lib\site-packages\pyclean\py3clean.py", line 31, in <module>
    from debpython import files as dpf
ModuleNotFoundError: No module named 'debpython'
```

**Comment by bittner** [comment]
The legacy  implementations, including `py3clean`, are for Debian Linux only (please [see the README](https://github.com/bittner/pyclean#debian) for details); they require a `debpython` module, which is available on Debian. Those scripts are included mainly for historical completeness, and are meant to be removed with the next major release (see the [Development Roadmap](https://github.com/bittner/pyclean#development) in the README). Don't use them, especially on systems other than Debian Linux.

Simply run `pyclean` for the pure-Python implementation. This will work even on Windows.
